import type { NextPage } from 'next'
import { signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import WalletConnectProvider from '@walletconnect/web3-provider'
import Web3Modal from 'web3modal'
import styles from '../styles/Home.module.css'

/* web3Modal configuration for enabling wallet access */
async function getWeb3Modal() {
  const web3Modal = new Web3Modal({
    cacheProvider: false,
    providerOptions: {
      walletconnect: {
        package: WalletConnectProvider,
        options: {
          infuraId: 'your-infura-id',
        },
      },
    },
  })
  return web3Modal
}

const Home: NextPage = () => {
  const { data: session, status } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">DeFi PnL</Link> Dashboard
        </h1>

        {status === 'authenticated' && (
          <div>
            <button onClick={() => signOut()}>Sign out</button>
          </div>
        )}

        <p className={styles.description}>
          Please, log in first with your wallet and pay 0.01 ETH one-time fee to
          access your DeFi PnL dashboard.
        </p>

        <div className={styles.grid}>
          <Link href="/dashboard">
            <div className={styles.card}>
              <h2>Access Dashboard &rarr;</h2>
              <p>Access your DeFi PnL dashboard with this link.</p>
            </div>
          </Link>

          <Link href="/signin">
            <div className={styles.card}>
              <h2>Sign in &rarr;</h2>
              <p>Sign in to access your account!</p>
            </div>
          </Link>
        </div>

        <div className="mt-3">
          {status && (
            <div>
              <strong>Status</strong>
              <pre>{JSON.stringify({ status })}</pre>
            </div>
          )}

          {session && (
            <div>
              <strong>Sesion data</strong>
              <pre>{JSON.stringify(session, null, 2)}</pre>
            </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
